name: Unit Tests
on:
  workflow_call:
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: pnpm i
      - run: pnpm test
